### ISSUE TITLE
访问 8000 端口 csr 模式，改动 web/layout 文件夹名称会报错，找不到 /node_modules/yk-cli/dist/Layout.server.js

### ISSUE THREAD

**Issue by JohannLai** [ykfe/egg-react-ssr#101]
报错如下：
```bash
(node:24001) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/data/workSpace/wecard-homepage-ssr/node_modules/yk-cli/dist/Layout.server.js'
[1]     at Object.openSync (fs.js:443:3)
[1]     at Object.readFileSync (fs.js:343:35)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:20)
[1]     at Module.load (internal/modules/cjs/loader.js:653:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[1]     at Module.require (internal/modules/cjs/loader.js:692:17)
[1]     at require (internal/modules/cjs/helpers.js:25:18)
[1]     at renderLayout (/data/workSpace/wecard-homepage-ssr/node_modules/yk-cli/lib/renderLayout.js:49:18)
[1] (node:24001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by zhangyuang** [comment]
改动文件夹名称需要同步修改paths.js中基准文件夹路径

**Comment by JohannLai** [comment]
感谢@zhangyuang回复，不过我看 paths.js 底下好像没有申明layout文件夹欸，我把 `web/layout` 改成 `web/layouts` 就报上面的错了  😭

**Comment by zhangyuang** [comment]
不支持自定义layout文件夹名称，web目录名称可以改

**Comment by JohannLai** [comment]
ok~ 明白，感谢 🌹
