### ISSUE TITLE
serverRender 使用 mobx-react 出现 hook 错误

### ISSUE THREAD

**Issue by JohannLai** [ykfe/egg-react-ssr#106]
hi，你好，可能是我使用不当出现以下问题，麻烦指导一下，感谢~
操作系统：centos7
使用语言： typescript

package.json
```json
  "dependencies": {
    "egg-scripts": "^2.10.0",
    "midway": "^1.0.0",
    "mobx": "^5.13.0",
    "mobx-react": "^6.1.4",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-router-dom": "^5.1.2",
    "yk-cli": "^2.6.0",
    "ykfe-utils": "^2.1.2"
  },
```

复现步骤：
1.  新建一个 typescript 的 ssr 项目
1. 加入以下内容:
1. npm start

```tsx
import { Provider, useStaticRendering } from 'mobx-react';


const serverRender = async (ctx: Context): Promise<JSX.Element> => {
  useStaticRendering(true);
  // 服务端渲染 根据ctx.path获取请求的具体组件，调用getInitialProps并渲染
  const ActiveComponent = getComponent(routes, ctx.path)()
  const Layout = ActiveComponent.Layout || defaultLayout
  const serverData = ActiveComponent.getInitialProps ? await ActiveComponent.getInitialProps(ctx) : {}
  ctx.serverData = serverData
  return  <Provider Index={{test: 111}} >
            <StaticRouter location={ctx.req.url} context={serverData}>
                <Layout layoutData={ctx}>
                    <ActiveComponent {...serverData} />
                </Layout>
            </StaticRouter>
        </Provider>
}
```

错误日志：
```
019-11-22 10:39:02,015 ERROR 22235 [-/10.13.82.114/-/130ms GET /] nodejs.Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
[0] [0] 1. You might have mismatching versions of React and the renderer (such as React DOM)
[0] [0] 2. You might be breaking the Rules of Hooks
[0] [0] 3. You might have more than one copy of React in the same app
[0] [0] See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
[0] [0] 1. You might have mismatching versions of React and the renderer (such as React DOM)
[0] [0] 2. You might be breaking the Rules of Hooks
[0] [0] 3. You might have more than one copy of React in the same app
[0] [0] See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
[0] [0]     at resolveDispatcher (webpack-internal:///./node_modules/react/cjs/react.development.js:1590:13)
[0] [0]     at Object.useContext (webpack-internal:///./node_modules/react/cjs/react.development.js:1598:20)
[0] [0]     at X (webpack-internal:///./node_modules/mobx-react/dist/mobx-react.module.js:26:5804)
[0] [0]     at processChild (/data/workSpace/test-mobx-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3204:14)
[0] [0]     at resolve (/data/workSpace/test-mobx-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3124:5)
[0] [0]     at ReactDOMServerRenderer.render (/data/workSpace/test-mobx-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:22)
[0] [0]     at ReactDOMServerRenderer.read (/data/workSpace/test-mobx-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
[0] [0]     at ReactMarkupReadableStream._read (/data/workSpace/test-mobx-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:38)
[0] [0]     at ReactMarkupReadableStream.Readable.read (_stream_readable.js:470:10)
[0] [0]     at resume_ (_stream_readable.js:949:12)
[0] [0] headerSent: true
[0] [0] pid: 22235
[0] [0] hostname: VM_9_43_centos
[0] [0] 
```

**Comment by zhangyuang** [comment]
请提供复现仓库，可以对比下example/ssr-with-mobx这个项目。

**Comment by JohannLai** [comment]
@zhangyuang 麻烦帮忙看看，同时我也对比一下

https://github.com/JohannLai/test-mobx-ssr/blob/fcade7c28629139ea393524f3ff3fbe4fb91bdfc/web/entry.tsx#L41

**Comment by zhangyuang** [comment]
ts的example有个bug，在昨天修复了。麻烦重新init一边项目就是正确的了
可以看这个[commit](https://github.com/ykfe/egg-react-ssr/commit/758e9d652dfa6251953cce96e1212709885c5188)手动修改也行

**Comment by JohannLai** [comment]
it works， thanks
