### ISSUE TITLE
ts 新项目启动失败

### ISSUE THREAD

**Issue by xiekw2010** [ykfe/egg-react-ssr#135]
按照文档 

http://ykfe.net/guide/gettingStarted.html#%E5%88%9B%E5%BB%BA%E5%BA%94%E7%94%A8

```js
$ npm install yk-cli -g
$ ykcli init <Your Project Name>
$ cd <Your Project Name>
$ npm i
$ npm start
$ open http://localhost:7001
```

启动失败：
```js
 concurrently "cross-env NODE_ENV=development midway-bin dev --ts" "cross-env NODE_ENV=development webpack --watch --config ./build/webpack.config.server.js"

[1] 
[1] webpack is watching the files...
[1] 
[0] 
[0] /Users/xkw/Desktop/ykok/node_modules/_egg-bin@4.14.0@egg-bin/lib/start-cluster:8
[0] require(options.framework).startCluster(options);
[0]                            ^
[0] TypeError: require(...).startCluster is not a function
[0]     at Object.<anonymous> (/Users/xkw/Desktop/ykok/node_modules/_egg-bin@4.14.0@egg-bin/lib/start-cluster:8:28)
[0]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
[0]     at startup (internal/bootstrap/node.js:283:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[0] { Error: /Users/xkw/Desktop/ykok/node_modules/_egg-bin@4.14.0@egg-bin/lib/start-cluster {"typescript":true,"workers":1,"framework":"/Users/xkw/Desktop/ykok/node_modules/midway","baseDir":"/Users/xkw/Desktop/ykok"} exit with code 1
[0]     at ChildProcess.proc.once.code (/Users/xkw/Desktop/ykok/node_modules/_common-bin@2.8.2@common-bin/lib/helper.js:56:21)
[0]     at Object.onceWrapper (events.js:273:13)
[0]     at ChildProcess.emit (events.js:182:13)
[0]     at ChildProcess.EventEmitter.emit (domain.js:441:20)
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12) code: 1 }
[0] cross-env NODE_ENV=development midway-bin dev --ts exited with code 1
[1] Hash: b6d1a6e9f0cf4a3d0815
[1] Version: webpack 4.19.1
[1] Time: 2491ms
[1] Built at: 12/17/2019 2:08:08 PM
[1]               Asset       Size  Chunks             Chunk Names
[1] static/css/Page.css  967 bytes    Page  [emitted]  Page
[1]      Page.server.js   55.7 KiB    Page  [emitted]  Page
[1] [./config/config.ssr.js] 1.02 KiB {Page} [built]
[1] [./web/assets/common.less] 329 bytes {Page} [built]
[1] [./web/entry.tsx] 4.28 KiB {Page} [built]
[1] [./web/layout/index.less] 329 bytes {Page} [built]
[1] [./web/layout/index.tsx] 3.63 KiB {Page} [built]
[1] [./web/page/index/index.less] 332 bytes {Page} [built]
[1] [./web/page/index/index.tsx] 2.24 KiB {Page} [built]
[1] [./web/page/news/index.tsx] 1.63 KiB {Page} [built]
[1] [path] external "path" 42 bytes {Page} [built]
[1] [react] external "react" 42 bytes {Page} [built]
[1] [react-dom] external "react-dom" 42 bytes {Page} [built]
[1] [react-router-dom] external "react-router-dom" 42 bytes {Page} [built]
[1] [regenerator-runtime] external "regenerator-runtime" 42 bytes {Page} [built]
[1] [serialize-javascript] external "serialize-javascript" 42 bytes {Page} [built]
[1] [ykfe-utils] external "ykfe-utils" 42 bytes {Page} [built]

```

**Comment by zhangyuang** [comment]
不要用内部的源。内部的midway这个包是很老的。
