### ISSUE TITLE
config.ssr生产环境路径问题

### ISSUE THREAD

**Issue by ellice** [ykfe/egg-react-ssr#201]
![image](https://user-images.githubusercontent.com/3806068/99144609-32933e00-26a2-11eb-99a7-3413c60e8b23.png)

`[react-dom] external "react-dom" 42 bytes {Page} [built]
[0] [1] [react-router-dom] external "react-router-dom" 42 bytes {Page} [built]
[0] [1] [serialize-javascript] external "serialize-javascript" 42 bytes {Page} {Layout} [built]
[0] [1] [ykfe-utils] external "ykfe-utils" 42 bytes {Page} [built]
[0] [1]     + 42 hidden modules
[0] [0] Error: Cannot find module '../../../../config/config.ssr'
[0] [0] Require stack:
[0] [0] - /Volumes/data/wsbb.web.server/src/app/controller/faqs.ts
[0] [0] - /Volumes/data/wsbb.web.server/node_modules/midway-core/dist/container.js
[0] [0] - /Volumes/data/wsbb.web.server/node_modules/midway-core/dist/loader.js
[0] [0] - /Volumes/data/wsbb.web.server/node_modules/midway-core/dist/index.js
[0] [0] - /Volumes/data/wsbb.web.server/node_modules/midway-web/dist/index.js
[0] [0] - /Volumes/data/wsbb.web.server/node_modules/midway/dist/index.js
[0] [0] - /Volumes/data/wsbb.web.server/node_modules/egg-cluster/lib/agent_worker.js
[0] [0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
[0] [0]     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
[0] [0]     at Module.require (internal/modules/cjs/loader.js:903:19)
[0] [0]     at require (internal/modules/cjs/helpers.js:74:18)
[0] [0]     at Object.<anonymous> (/Volumes/data/wsbb.web.server/src/app/controller/faqs.ts:8:27)
[0] [0]     at Module._compile (internal/modules/cjs/loader.js:1015:30)
[0] [0]     at Module.m._compile (/Volumes/data/wsbb.web.server/node_modules/ts-node/src/index.ts:439:23)
[0] [0]     at Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
[0] [0]     at Object.require.extensions.<computed> [as .ts] (/Volumes/data/wsbb.web.server/node_modules/ts-node/src/index.ts:442:12)
[0] [0]     at Module.load (internal/modules/cjs/loader.js:879:32)
[0] [0] 2020-11-14 17:50:44,381 ERROR 43460 nodejs.AgentWorkerDiedError: [master] agent_worker#1:43464 died (code: 1, signal: null)
[0] [0]     at Master.onAgentExit (/Volumes/data/wsbb.web.server/node_modules/egg-cluster/lib/master.js:425:17)
[0] [0]     at Master.emit (events.js:314:20)
[0] [0]     at Messenger.sendToMaster (/Volumes/data/wsbb.web.server/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[0] [0]     at Messenger.send (/Volumes/data/wsbb.web.server/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[0] [0]     at ChildProcess.<anonymous> (/Volumes/data/wsbb.web.server/node_modules/egg-cluster/lib/master.js:289:22)
[0] [0]     at Object.onceWrapper (events.js:421:26)
[0] [0]     at ChildProcess.emit (events.js:314:20)
[0] [0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[0] [0] name: "AgentWorkerDiedError"`

npm init ssr-app my-ssr-project --template=ssr-with-ts 项目添加antd-mobile 后 config.ssr路径问题。  yarn start的可以编译通过   yarn run prod 找不到路径

**Comment by zhangyuang** [comment]
给复现仓库

**Comment by ellice** [comment]
> 给复现仓库

git@github.com:ellice/ssr-antd-mobile.git

**Comment by zhangyuang** [comment]
不要在src目录以外创建ts文件(config/config.ts文件错了，直接用src/config下面的配置文件即可)。导致了midway build出来的路径层级不符合预期
