### ISSUE TITLE
在example中的ssr-with-ts项目里yarn prod 之后报错

### ISSUE THREAD

**Issue by rexchen94** [ykfe/egg-react-ssr#210]
错误信息：
前端路由已经自动绑定，规则如下：
 /=>page.index
Error: write EPIPE
    at process.target._send (internal/child_process.js:832:20)
    at process.target.send (internal/child_process.js:703:19)
    at Object.<anonymous> (/Users/yaochen/egg-react-ssr/example/ssr-with-ts/node_modules/egg-cluster/lib/app_worker.js:28:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
2021-03-12 13:59:19,438 ERROR 69829 [app_worker] exit with code:1
 /news/:id=>page.index
➜  ssr-with-ts git:(dev) 2021-03-12 13:59:19,445 INFO 69830 [egg:core] dump config after load, 6ms
Error: write EPIPE
    at process.target._send (internal/child_process.js:832:20)
    at process.target.send (internal/child_process.js:703:19)
    at Object.<anonymous> (/Users/yaochen/egg-react-ssr/example/ssr-with-ts/node_modules/egg-cluster/lib/app_worker.js:28:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
2021-03-12 13:59:19,450 ERROR 69830 [app_worker] exit with code:1

**Comment by zhangyuang** [comment]
本地试了一下example是ok的，无法复现，可以给个复现仓库。另外如果是新项目现在是比较推荐用这套解决方案的。https://github.com/ykfe/ssr
